### ISSUE TITLE
no @if replace

### ISSUE THREAD

**Issue by harikt** [impiix/blade2twig#2]
There is missing @if condition.

**Comment by harikt** [comment]
If is a bit tricky here. And need some good unit tests.

Something like the below is very basic functionality 

`@if\s*\(([$]+)?(.*)\)` => `{% if $2 %}`

**Comment by impiix** [comment]
Wouldn't this be a bit simpler, it should do the same thing
`@if\s*\(\$*(.*)\)` => `{% if $1 %}`

**Comment by harikt** [comment]
> Wouldn't this be a bit simpler, it should do the same thing
@if\s*\(\$*(.*)\) => {% if $1 %}

Yes, nice.

I noticed a bit more issues or need to be addressed. I think you may be already knowing. Or do you want to open issues separately ?

**Comment by impiix** [comment]
What about posting a list into separate thread.
